title: <p align="center"> Ashutosh Kulkarni </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/aashutoshk/">LinkedIn</a> |
  <a href="https://github.com/aashukul9">GitHub</a>
  
  <br> 
  I/m workng as full stack developer.
  I have statred learning about Data Science, Machine learning recently.
  <br>
  </p>



theme: jekyll-theme-minimal
